@tool
extends RefCounted

const SEVERITY_GROUPS := [
    {"id": "error", "label": "Errors"},
    {"id": "warning", "label": "Warnings"},
    {"id": "info", "label": "Info"}
]

func write(report: Dictionary, output_path: String) -> bool:
    var file := FileAccess.open(output_path, FileAccess.WRITE)
    if file == null:
        push_error("Could not write Markdown report: %s" % output_path)
        return false

    var summary: Dictionary = report.get("summary", {})
    var lines: Array[String] = []
    lines.append("# Godot Project Doctor Report")
    lines.append("")
    lines.append("Generated: %s" % _sanitize_text(report.get("generated_at", "")))
    lines.append("Project: %s" % _sanitize_text(report.get("project_root", "res://")))
    lines.append("Scan Duration: %d ms" % int(report.get("scan_duration_ms", 0)))
    lines.append("")
    lines.append("## Generated By")
    lines.append("")
    lines.append("- Tool: %s" % _sanitize_text(report.get("tool", "Godot Project Doctor Mini")))
    lines.append("- Version: %s" % _sanitize_text(report.get("tool_version", "unknown")))
    lines.append("")
    lines.append("## Summary")
    lines.append("")
    lines.append("| Severity | Count |")
    lines.append("| --- | ---: |")
    lines.append("| Error | %d |" % summary.get("errors", 0))
    lines.append("| Warning | %d |" % summary.get("warnings", 0))
    lines.append("| Info | %d |" % summary.get("info", 0))
    lines.append("")
    lines.append("## Findings")
    lines.append("")

    var findings: Array = report.get("findings", [])
    if findings.is_empty():
        lines.append("No findings.")
    else:
        var grouped_findings := _group_findings_by_severity(findings)
        for group in SEVERITY_GROUPS:
            var severity_id := str(group.get("id", "info"))
            var severity_label := str(group.get("label", severity_id.capitalize()))
            var severity_findings: Array = grouped_findings.get(severity_id, [])
            if severity_findings.is_empty():
                continue

            lines.append("<details open>")
            lines.append("<summary>%s (%d)</summary>" % [severity_label, severity_findings.size()])
            lines.append("")
            lines.append("| Finding | Path | Check | Message | Recommendation |")
            lines.append("| --- | --- | --- | --- | --- |")
            for finding_variant in severity_findings:
                var finding: Dictionary = finding_variant
                lines.append("| %s | %s | %s | %s | %s |" % [
                    _sanitize_table_cell(finding.get("title", "Finding")),
                    _sanitize_table_cell(finding.get("path", "")),
                    _sanitize_table_cell(finding.get("id", "unknown")),
                    _sanitize_table_cell(finding.get("message", "")),
                    _sanitize_table_cell(finding.get("recommendation", ""))
                ])
            lines.append("")
            lines.append("</details>")
            lines.append("")

    file.store_string("\n".join(lines))
    return true

func _group_findings_by_severity(findings: Array) -> Dictionary:
    var grouped := {
        "error": [],
        "warning": [],
        "info": []
    }

    for finding_variant in findings:
        if typeof(finding_variant) != TYPE_DICTIONARY:
            continue

        var finding: Dictionary = finding_variant
        var severity := str(finding.get("severity", "info"))
        if not grouped.has(severity):
            severity = "info"
        grouped[severity].append(finding)

    return grouped

func _sanitize_text(value: Variant) -> String:
    return str(value).replace("\\", "\\\\").replace("\r\n", " ").replace("\n", " ").replace("|", "\\|").replace("`", "\\`").strip_edges()

func _sanitize_table_cell(value: Variant) -> String:
    var text := str(value).strip_edges()
    if text == "":
        return "-"

    return text.replace("\\", "\\\\").replace("\r\n", "<br>").replace("\n", "<br>").replace("|", "\\|").replace("`", "\\`").strip_edges()
